### ISSUE TITLE
fofa is using cookies 

### ISSUE THREAD

**Issue by m7jalta** [Cl0udG0d/Fofa-python-#3]
I cant find Authorization on headers only cookies

**Comment by Cl0udG0d** [comment]
I think you can take a look at this issue
>   [Authorization找不到 ](https://github.com/Cl0udG0d/Fofa-script/issues/2)

At the same time I tested again
**step1**: login fofa
**step2**: input your search keyword (for example,i input title="Solr Admin")
![image](https://user-images.githubusercontent.com/45556496/122855003-1f86d180-d347-11eb-84f8-3d99d9bd34b9.png)

**step3**: click on F12,open browser console network,refresh page
**step4**: find fofa api site : `https://api.fofa.so/v1/search/stats`，and Authorization always in the second api URL
![image](https://user-images.githubusercontent.com/45556496/122854973-185fc380-d347-11eb-87d7-8814c5713646.png)
**step5**: use this tool

If you can solve it successfully, please reply to me so that I can close the issue
